"""Changing repository tbale to fit github integration

Revision ID: 48a66d7a4fb1
Revises: 78ec3363dd2f
Create Date: 2026-06-16 17:57:57.205792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a66d7a4fb1'
down_revision: Union[str, Sequence[str], None] = '78ec3363dd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('github_repo_id', sa.Integer(), nullable=False))
    op.add_column('repositories', sa.Column('clone_url', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('default_branch', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('private', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'private')
    op.drop_column('repositories', 'default_branch')
    op.drop_column('repositories', 'clone_url')
    op.drop_column('repositories', 'github_repo_id')
    # ### end Alembic commands ###
