"""Adding condition to workflowStep

Revision ID: 51cdcf5c17f9
Revises: 8d348c90b448
Create Date: 2026-06-20 20:05:08.065328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cdcf5c17f9'
down_revision: Union[str, Sequence[str], None] = '8d348c90b448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_steps', sa.Column('condition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'condition')
    # ### end Alembic commands ###
