"""Connecting repositories with foreign key user id

Revision ID: 552d70a9cf1d
Revises: b89cd0dbf1ed
Create Date: 2026-06-08 12:44:41.294523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552d70a9cf1d'
down_revision: Union[str, Sequence[str], None] = 'b89cd0dbf1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'repositories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'user_id')
    # ### end Alembic commands ###
