"""add github user fields

Revision ID: f45e195d1979
Revises: 70ea76fd95ba
Create Date: 2026-06-15 14:23:21.886655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45e195d1979'
down_revision: Union[str, Sequence[str], None] = '70ea76fd95ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('github_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_access_token')
    op.drop_column('users', 'github_username')
    # ### end Alembic commands ###
